name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'qmhc/event-modifier'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Publish package
        run: pnpm run publish:ci ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096
